### ISSUE TITLE
how can I set the path for load the file? 

### ISSUE THREAD

**Issue by moebiussurfing** [iwanao731/of-ARAP#1]
```
	igl::readOBJ("data/armadillo.obj", V, F);

	convertMesh_IGL2OF(V, F, mMesh);

	U = V;
	MatrixXd W;
	igl::readDMAT("data/armadillo-weights.dmat", W);
```
`IOError: data/armadillo.obj could not be opened...`

i added data/data/armadillo.obj
I also tried ofSetWorkingDirectoryToDefault(); in main.m
and ofRestoreWorkingDirectoryToDefault();
ofEnableDataPath(); in ofApp

nothing works...
I am on macOS and OF GitHub

just curious to check your meshes tools
any idea?

**Comment by iwanao731** [comment]
Thanks for message. I fixed the loading issue on MACOS.
Please check it:)

**Comment by moebiussurfing** [comment]
thanks, it worked. just needed to add ofxEigen to addons.make too.
it's not intended to work in realtime but it's really nice!
